// Pure ffmpeg argument builders for the Video Trim tool (no DOM / no ffmpeg import: unit-testable).

export interface Segment {
	start: number;
	end: number;
}

export type OutputKind = 'video' | 'gif' | 'mp3';

export const SPEED_OPTIONS = [0.5, 0.75, 1, 1.25, 1.5, 2, 4] as const;
export const HEIGHT_OPTIONS = [0, 1080, 720, 480, 360] as const; // 0 = keep original
export const GIF_FPS_OPTIONS = [5, 10, 15, 20] as const;
export const GIF_WIDTH_OPTIONS = [240, 320, 480, 640] as const;
export const MP3_BITRATE_OPTIONS = [128, 192, 256, 320] as const;
export const DEFAULT_CRF = 23;
export const MAX_SEGMENTS = 20;
export const MIN_SEGMENT_GAP = 0.1;

export interface VideoOptions {
	mode: 'fast' | 'precise';
	mute: boolean;
	speed: number;
	/** Max output height in px; 0 keeps the original size. */
	height: number;
	crf: number;
}

const sec = (n: number) => n.toFixed(3);

/** Speed change and resizing cannot be done with stream copy. */
export function needsReencode(o: Pick<VideoOptions, 'speed' | 'height'>): boolean {
	return o.speed !== 1 || o.height > 0;
}

export function effectiveMode(o: VideoOptions): 'fast' | 'precise' {
	return o.mode === 'precise' || needsReencode(o) ? 'precise' : 'fast';
}

/** atempo only accepts 0.5..2.0 per instance, so larger/smaller factors are chained. */
export function atempoChain(speed: number): string[] {
	if (!(speed > 0) || speed === 1) return [];
	const filters: string[] = [];
	let remaining = speed;
	while (remaining > 2) {
		filters.push('atempo=2');
		remaining /= 2;
	}
	while (remaining < 0.5) {
		filters.push('atempo=0.5');
		remaining /= 0.5;
	}
	filters.push(`atempo=${Number(remaining.toFixed(4))}`);
	return filters;
}

export function buildVideoFilter(o: Pick<VideoOptions, 'speed' | 'height'>): string {
	const filters: string[] = [];
	if (o.speed !== 1) filters.push(`setpts=PTS/${o.speed}`);
	// "\," keeps the comma inside min() from being read as a filter separator.
	if (o.height > 0) filters.push(`scale=-2:min(${o.height}\\,ih)`);
	return filters.join(',');
}

export function buildAudioFilter(o: Pick<VideoOptions, 'speed'>): string {
	return atempoChain(o.speed).join(',');
}

/** Args that cut one segment out of `input` into `output` (stream copy or H.264/AAC re-encode). */
export function buildSegmentArgs(input: string, output: string, seg: Segment, o: VideoOptions): string[] {
	const pre = ['-ss', sec(seg.start), '-i', input, '-t', sec(seg.end - seg.start)];
	if (effectiveMode(o) === 'fast') {
		return [...pre, '-c', 'copy', '-avoid_negative_ts', 'make_zero', ...(o.mute ? ['-an'] : []), output];
	}
	const vf = buildVideoFilter(o);
	const af = buildAudioFilter(o);
	return [
		...pre,
		...(vf ? ['-vf', vf] : []),
		...(o.mute ? ['-an'] : af ? ['-af', af] : []),
		'-c:v',
		'libx264',
		'-preset',
		'ultrafast',
		'-crf',
		String(o.crf),
		'-pix_fmt',
		'yuv420p',
		...(o.mute ? [] : ['-c:a', 'aac']),
		'-movflags',
		'+faststart',
		output,
	];
}

/** Text of an ffmpeg concat-demuxer list file. Names are virtual-FS names generated by us (no quotes). */
export function buildConcatList(names: string[]): string {
	return names.map((n) => `file '${n}'`).join('\n') + '\n';
}

export function buildConcatArgs(listName: string, output: string): string[] {
	return ['-f', 'concat', '-safe', '0', '-i', listName, '-c', 'copy', output];
}

/** Input spec: either the original file cut on the fly, or an already-merged intermediate file. */
export interface MediaSource {
	input: string;
	cut?: Segment;
}

function sourceArgs(src: MediaSource): string[] {
	return src.cut ? ['-ss', sec(src.cut.start), '-i', src.input, '-t', sec(src.cut.end - src.cut.start)] : ['-i', src.input];
}

export function buildGifArgs(
	src: MediaSource,
	opts: { fps: number; width: number; speed: number },
	output: string,
): string[] {
	const chain = [
		...(opts.speed !== 1 ? [`setpts=PTS/${opts.speed}`] : []),
		`fps=${opts.fps}`,
		`scale=min(${opts.width}\\,iw):-1:flags=lanczos`,
	].join(',');
	// Two-pass palette inside one graph: palettegen builds an optimal 256-colour palette, paletteuse applies it.
	const graph = `${chain},split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse`;
	return [...sourceArgs(src), '-vf', graph, '-loop', '0', output];
}

export function buildMp3Args(src: MediaSource, opts: { bitrate: number; speed: number }, output: string): string[] {
	const af = buildAudioFilter(opts);
	return [...sourceArgs(src), '-vn', ...(af ? ['-af', af] : []), '-c:a', 'libmp3lame', '-b:a', `${opts.bitrate}k`, output];
}

export function totalSegmentsDuration(segments: Segment[]): number {
	return segments.reduce((sum, s) => sum + Math.max(0, s.end - s.start), 0);
}

/** True when every segment is inside [0, duration] with a positive length. */
export function segmentsValid(segments: Segment[], duration: number): boolean {
	return (
		segments.length > 0 &&
		segments.every((s) => Number.isFinite(s.start) && Number.isFinite(s.end) && s.start >= 0 && s.end - s.start >= MIN_SEGMENT_GAP / 2 && s.end <= duration + 0.001)
	);
}

/** New segment placed after the last one (about 10% of the video, at least 1 s); null if no room. */
export function nextSegment(segments: Segment[], duration: number): Segment | null {
	if (segments.length >= MAX_SEGMENTS || duration <= 0) return null;
	const lastEnd = segments.reduce((max, s) => Math.max(max, s.end), 0);
	const room = duration - lastEnd;
	if (room < MIN_SEGMENT_GAP * 2) {
		// No free tail: fall back to a copy of the first part of the video.
		const len = Math.min(duration, Math.max(1, duration * 0.1));
		return { start: 0, end: len };
	}
	const len = Math.min(room, Math.max(1, duration * 0.1));
	return { start: lastEnd, end: lastEnd + len };
}

export function outputExtension(kind: OutputKind, fallbackExt: string, o: VideoOptions): string {
	if (kind === 'gif') return 'gif';
	if (kind === 'mp3') return 'mp3';
	return effectiveMode(o) === 'fast' ? fallbackExt : 'mp4';
}

/** Evenly spaced capture times for the timeline thumbnail strip (centre of each slice). */
export function thumbnailTimes(duration: number, count: number): number[] {
	if (!(duration > 0) || count < 1) return [];
	return Array.from({ length: count }, (_, i) => Math.min(duration - 0.05, ((i + 0.5) / count) * duration)).map((t) => Math.max(0, t));
}

/** Frame step used by the +/-1 frame buttons: 1/fps, defaulting to 30 fps when unknown. */
export function frameStepSeconds(fps?: number): number {
	return fps && fps > 1 && fps <= 240 ? 1 / fps : 1 / 30;
}
